
## Server Properties
server:
  port: 8081
  servlet:
    context-path: /

#Spring Properties

spring:
  application:
    name: SpringSecurity-Data-Application
  servlet:
    multipart:
      enabled: false
      #file-size-threshold: 2KB
      max-file-size: -1
      max-request-size: -1


  # Jpa Properties
  datasource:
    url: jdbc:mysql://bcmc.cy8obdina40j.us-east-1.rds.amazonaws.com:3306/springdatademo?serverTimezone=UTC
    username: admin
    password: MIURsO1WJd2oNFin6jju
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        dialet: org.hibernate.dialect.MySQL8Dialect

  # Spring Session properties
  devtools:
    restart:
      enabled: true

